#!/bin/bash
# full and incremental backup script
# Copyright @hpsaturn

# Created 07 February 2000
# Based on a script by Daniel O'Callaghan <danny@freebsd.org>

# REVISIONS
# 20201024 Refactor names and comments
# 20191101 Main refactor, isolated options (for cron)
# 20121219 Autoconfigure via console paramaters
# 20130219 Add help

COMMAND="$1"                              # task to do: full, week, incremental
TAGNAME="$2"                              # backup name 
ROOT="$3"                                 # root of storage path
TARGET="$4"                               # directory to backup

SECONDARY="$5"                            # secondary storege path (optional)

################################################################################
##################### END OF CONFIGURATION #####################################
################################################################################

BACKUPDIR=$ROOT/$TAGNAME               # where to store the backups
TIMEDIR=$ROOT/$TAGNAME/last-full       # where to store time of full backup
TAR=/bin/tar                            # name and locaction of tar
IGNORE=$ROOT/$TAGNAME/ignorefiles      # ignore files

PATH=/usr/local/bin:/usr/bin:/bin
DOW=`date +%a`              		# Day of the week e.g. Mon
DOM=`date +%d`              		# Date of the Month e.g. 27
DM=`date +%d%b`             	  # Date and Month e.g. 27Sep
DATE=`date +%Y%m%d`             # Date format AAAAMMDD

# The full backup command add a full date format to output file
# The full week backup command overwrite the same incremental bkp with a new full bkp.
# Each icremental backup overwrites last weeks incremental backup of the same name.
#
# if NEWER = "", then tar backs up all files in the TARGET
# otherwise it backs up files newer than the NEWER date. NEWER
# gets it date from the file written on each full bkp.

function showHelp(){
    echo ""
    echo "Usage: backup [command] tagname storage target [optional storage]"
    echo ""
    echo "Example simple:       backup full home /bkp /home/user" 
    echo "Example dual storage: backup full home /bkp /home/user /mnt/samba/bkp" 
    echo ""
    echo "Example: installing in crontab:"
    echo "00  19  *   *   *   /home/user/bin/backup increm home /bkp /home/user"
    echo "00  20  *   *   0   /home/user/bin/backup week home /bkp /home/user"
    echo ""
    echo "Commands:"
    echo ""
    echo "full: Full backup, output with complete date name file" 
    echo "week: Week full backup, output with day name file"
    echo "increm: Incremental backup respect last full backup (week or full)"
    echo "init: create empty tagname directory structure on storage directory"
    echo ""
}

function checkdirs () {
  if [ "$TAGNAME" == "" ]; then
    showHelp   
    exit 3
  fi

  if [[ ( "$ROOT" == "" ) || ( "$TARGET" == "" ) ]]; then
    echo ""
    echo "ERROR: Root backup directory or target directory not found!"
    showHelp
    exit 3
  fi

  if [ ! -d "$ROOT/$TAGNAME" ]; then
    echo -n "CREATING ROOT BACKUP: $ROOT"
    mkdir -p $ROOT/$TAGNAME
    INITBKP=1
    echo " [OK]"
  fi

  if [ ! -d "$TIMEDIR" ]; then
    echo -n "CONFIGURE TIME DIRECTORY: $TIMEDIR"
    mkdir -p $TIMEDIR
    NOW=`date +%d-%b`
    echo $NOW > $TIMEDIR/$TAGNAME-full-date
    echo " [OK]"
  fi

  if [ ! -f "$IGNORE" ]; then
    echo -n "CREATING IGNORE CONFIG FILE: $IGNORE"
    touch $IGNORE
    echo " [OK]"
  fi

  if [ "$SECONDARY" != "" ]; then

    if [ ! -d "$SECONDARY/$TAGNAME" ]; then
      echo -n "CREATING SECONDARY BACKUP: $SECONDARY"
      mkdir -p $SECONDARY/$TAGNAME
      echo " [OK]"
      echo ""
    fi
  fi
}

function runbackup () {
  echo "ignore file path ==> $IGNORE"
  echo "target dir  path ==> $TARGET"
  $TAR $NEWER -zcf $FILE --exclude-from=$IGNORE $TARGET

  if [ "$SECONDARY" != "" ]; then
    echo "copy to secondary ==> $SECONDARY/$TAGNAME"
    cp -f $FILE $SECONDARY/$TAGNAME/
  fi
}

function cleanfile () {
  if [ -f $FILE ]; then
    rm $FILE
  fi
}

function updatelastdate () {
  # Update full backup date (/tmp for samba)
  NOW=`date +%d-%b` 
  echo $NOW > /tmp/$TAGNAME-full-date
  mv /tmp/$TAGNAME-full-date $TIMEDIR/
}

# Monthly full backup
function runfullbkp () {
  NEWER=""
  FILE=$BACKUPDIR/bkp_$TAGNAME_$DATE.tar.gz
  echo "Monthly full backup ==> $FILE"
  cleanfile
  runbackup
  updatelastdate
}

# Weekly full backup
function runfullweekbkp () {
  NEWER=""
  FILE=$BACKUPDIR/$TAGNAME-$DOW.tar.gz
  echo "Weekly full backup ==> $FILE"
  cleanfile
  runbackup
  updatelastdate
}

# Make incremental backup - overwrite last weeks
function runincrementalbkp () {
  # Get date of last full backup
  NEWER="--newer `cat $TIMEDIR/$TAGNAME-full-date`"
  FILE=$BACKUPDIR/$TAGNAME-$DOW.tar.gz
  echo "Incremental backup ==> $FILE"
  cleanfile
  runbackup
}

# Monthly full backup
function runinit () {
  NEWER=""
  FILE=$BACKUPDIR/bkp_$TAGNAME_$DATE.tar.gz
  echo "Creating empty directory for $BACKUPDIR"
  cleanfile
  updatelastdate
}

checkdirs

case "$COMMAND" in
  full)
    runfullbkp
    ;;
  week)
    runfullweekbkp
    ;;
  increm)
    runincrementalbkp
    ;;
  init)
    runinit
    ;;
  *)
    showHelp
    ;;
esac

