#!/bin/bash
##########################################################
# @hpsaturn 20180806
#
# Prerequisits:
# docker image: https://github.com/sh1r0/caffe-android-lib
##########################################################


print_header(){
    echo ""
    echo "*****************************"
    echo "****   $1    *****"
    echo "*****************************"
    echo ""
}

rm -rf ./android_lib

print_header "  ARMEABI  "
docker run --rm --name caffe-android-builder -e ANDROID_ABI=armeabi -e N_JOBS=2 -v $(pwd)/android_lib/armeabi:/caffe-android-lib/android_lib caffe-android-lib ./build_opencv.sh

print_header "ARMEABI-V7A"
docker run --rm --name caffe-android-builder -e ANDROID_ABI=armeabi-v7a -e N_JOBS=2 -v $(pwd)/android_lib/armeabi-v7a:/caffe-android-lib/android_lib caffe-android-lib ./build_opencv.sh

print_header " ARM64-V8A "
docker run --rm --name caffe-android-builder -e ANDROID_ABI=arm64-v8a -e N_JOBS=2 -v $(pwd)/android_lib/arm64-v8a:/caffe-android-lib/android_lib caffe-android-lib ./build_opencv.sh

print_header "   X86    "
docker run --rm --name caffe-android-builder -e ANDROID_ABI=x86 -e N_JOBS=2 -v $(pwd)/android_lib/x86:/caffe-android-lib/android_lib caffe-android-lib ./build_opencv.sh

print_header "  X86_64   "
docker run --rm --name caffe-android-builder -e ANDROID_ABI=x86_64 -e N_JOBS=2 -v $(pwd)/android_lib/x86_64:/caffe-android-lib/android_lib caffe-android-lib ./build_opencv.sh

rm -rf ./tmp
mkdir -p ./tmp/android_lib
cp -r android_lib/armeabi/* tmp/android_lib/
cp -r android_lib/armeabi-v7a/* tmp/android_lib/
cp -r android_lib/arm64-v8a/* tmp/android_lib/
cp -r android_lib/x86/* tmp/android_lib/
cp -r android_lib/x86_64/* tmp/android_lib/

cd ./tmp/
DATE=`date +%Y%m%d`
tar jcf ../android_lib_multiarch$DATE.tar.bz2 android_lib
cd ..
rm -rf ./tmp

