#!/bin/bash
##########################################################
# @hpsaturn 20180806
#
# Prerequisits:
# docker image: https://github.com/sh1r0/caffe-android-lib
##########################################################

build_system="linux"
branch=`cd opencv && git describe && cd ..`

print_header(){
    echo ""
    echo "*****************************"
    echo "****   $1    *****"
    echo "*****************************"
    echo ""
}

print_details(){
  echo ""
  echo "DETAILS:"
  echo ""
  echo "config tools:"
  env | grep ANDROID
  echo ""
  echo "opencv branch:"
  echo "$branch"
  echo ""
  echo "output libraries:"
  du -hs tmp/android_lib/opencv/sdk/native/libs/*
  echo ""
}

clean () {
  sudo rm -rf ./android_lib
  mkdir ./android_lib
  sudo rm -rf ./tmp
  mkdir -p ./tmp/android_lib
}

build_arch_docker () {
  sudo rm -rf ./android_lib/$1
  docker run --rm --name caffe-android-builder -e ANDROID_ABI=$1 -e N_JOBS=2 -v $(pwd)/android_lib/$1:/caffe-android-lib/android_lib caffe-android-lib ./build_opencv.sh
  cp -r android_lib/$1/* tmp/android_lib/
  print_details
}

build_arch_linux () {
  sudo rm -rf ./android_lib/*
  export ANDROID_ABI=$1
  ./build_opencv.sh
  cp -r android_lib/* tmp/android_lib/
  print_header $1 
  print_details
}

build_arch () {
if [ "$build_system" = "linux" ]; then
  build_arch_linux "$1"
else
  build_arch_docker "$1"
fi
}

build_package () {
  cd tmp/
  DATE=`date +%Y%m%d`
  tar jcf ../android_lib_multiarch_$branch_$DATE.tar.bz2 android_lib
  cd ..
  du -hs android_lib_multiarch_$branch_$DATE.tar.bz2
}

build_all () {
  clean
  build_arch "armeabi"
  build_arch "armeabi-v7a"
  build_arch "arm64-v8a"
  build_arch "x86"
  build_arch "x86_64" 

  build_package
  print_details
}

build_image () {
  docker build -t caffe-android-lib . 
}

#########################################################
######################## MAIN ###########################
#########################################################

if [ "$1" = "" ]; then
  build_all
else
  mkdir -p ./android_lib
  mkdir -p ./tmp/android_lib

  case "$1" in
    armeabi)
      print_header "  ARMEABI  "
      build_arch $1
      ;;
    armeabi-v7a)
      print_header "ARMEABI-V7A"
      build_arch $1
      ;;
    arm64-v8a)
      print_header " ARM64-V8A "
      build_arch $1
      ;;
    x86)
      print_header "   X86    "
      build_arch $1
      ;;
    x86_64)
      print_header "  X86_64   "
      build_arch $1
      ;;
    clean)
      clean
      ;;
    package)
      print_details
      build_package
      ;;
    image)
      build_image
      ;;
  esac
fi

exit 0


