#!/bin/bash

if [ "$1" = "" ]; then
  echo "error: missing seconds parameter!"
  exit 1
fi

clear; for i in `seq $1 -1 1`; do  banner $i; sleep 1; clear; done ; play -n synth .8 sine 4100 fade q 0.1 .3 0.1 repeat 3 &> /dev/null
