#!/bin/bash

countdown_time=$1

hrs=0
min=0
sec=0

convert_seconds () {
  min=$(($1/60))
  sec=$(($1-($min*60)))
  hrs=$(($min/60))
  min=$(($min%60))

  sec=$(echo $sec | awk '{printf("%02d", $1)}')
  min=$(echo $min | awk '{printf("%02d", $1)}')
  hrs=$(echo $hrs | awk '{printf("%02d", $1)}')
}

play_sound () {
  for (( c=0; c<=2; c++)); do
    mpv --msg-level=statusline=status,all=error /home/avp/sounds_gaim/protoss_message.mp3
    sleep 0.5
  done
}

cstart=`date +%H:%M:%S.%3N`
countdown_time=$((countdown_time-1))

while [ $SECONDS -le $countdown_time ]; do
  clear
  convert_seconds $((countdown_time - SECONDS))
  figlet " $hrs : $min : $sec" ; sleep 0.3;
done

cstop=`date +%H:%M:%S.%3N`

printf " Countdown start\t: %s\r\n" $cstart
printf " Countdown stop \t: %s\r\n" $cstop
printf " Elapsed time   \t: %i secs\r\n\r\n" $((SECONDS))

if [ "$2" == "" ]; then
  play_sound
fi


