#!/bin/bash

SECONDS=$1

hrs=0
min=0
sec=0

convert_seconds () {
  min=$(($1/60))
  sec=$(($1-($min*60)))
  hrs=$(($min/60))
  min=$(($min%60))

  sec=$(echo $sec | awk '{printf("%02d", $1)}')
  min=$(echo $min | awk '{printf("%02d", $1)}')
  hrs=$(echo $hrs | awk '{printf("%02d", $1)}')
}

for i in `seq $SECONDS -1 0`; do  
  clear
  convert_seconds $i
  figlet "$hrs : $min : $sec" ; sleep 1;
done

#play -n synth .8 sine 4100 fade q 0.1 .3 0.1 repeat 3 &> /dev/null
for (( c=0; c<=2; c++)); do
  mplayer -msglevel all=-1 /home/avp/sounds_gaim/protoss_message.mp3
  sleep 0.5
done

