#! /bin/bash
set -o errexit

freecache () {
    msg="freecache:"
    sync
    sudo echo 3 > /proc/sys/vm/drop_caches &
    pidcache=$!
}

freeswap () {
    msg="freeswap:"
    swapoff -a &
    pidswap=$!
}

enableswap () {
    msg="freeswap:"
    swapon -a &
    pidswap=$!
}

whilep () {
    # If this script is killed, kill the `cp'.
    trap "kill $1 2> /dev/null" EXIT

    while kill -0 $1 2> /dev/null; do
        getchar
        buffval=`cat /proc/meminfo | grep Buffers | awk '{print $2}'`
        swapval=`cat /proc/meminfo | grep SwapCached | awk '{print $2}'`
        printf "%s [buffer:%07d][swap:%07d] %s\r" "$msg" "$buffval" "$swapval" "$statuschar"
        sleep 0.05
    done
    printf "                                                     \r"


}

StatusChar="/
|
\
-"

getchar(){
    denomination=($StatusChar)
    num_denominations=${#denomination[*]}
    statuschar="${denomination[$((RANDOM%num_denominations))]}"
}

######################################
############# M A I N ################
######################################

freecache
whilep $pidcache
freeswap
whilep $pidswap
sync
enableswap
whilep $pidswap






