#! /bin/bash
set -o errexit

freecache () {
    msg="freecache"
    sync
    sudo echo 3 > /proc/sys/vm/drop_caches &
    pidcache=$!
}

freeswap () {
    msg="freeswap "
    swapoff -a &
    pidswap=$!
}

enableswap () {
    msg="freeswap "
    swapon -a &
    pidswap=$!
}

whilep () {
    # If this script is killed, kill the `cp'.
    trap "kill $1 2> /dev/null" EXIT

    while kill -0 $1 2> /dev/null; do
        getchar
        printf "%s %s\r" "$msg" "$statuschar"
        sleep 0.1
    done
}

StatusChar="/
|
\
-"

getchar(){
    denomination=($StatusChar)
    num_denominations=${#denomination[*]}
    statuschar="${denomination[$((RANDOM%num_denominations))]}"
}

######################################
############# M A I N ################
######################################

freecache
whilep $pidcache
freeswap
whilep $pidswap
sync
enableswap
whilep $pidswap






