#!/bin/bash

xrandr --output HDMI1 --same-as eDP1 --primary --auto
sleep 2
xrandr --output eDP1 --off
sleep 2
kill -usr1 `pgrep wmaker | tail -1` # restart wmaker
sleep 2
xrandr --output eDP1 --right-of HDMI1 --auto
killall gkrellm
gkrellm -wm -g +1848+0 & 



