#! /bin/bash

execute_process () {
  printf "checking\t%.7s" "$1"
  pid=`pidof $1`
  prm=`ps aux | grep -e "$1 $2"`
  if [ "$pid" == "" ] ; then
    printf "\t\trestarting\n"
    eval "$1 $2" &> /dev/null &
  elif [ "$prm" == "" ] ; then 
    printf "\t\tnot same\n"
    printf  "executing\t%.7s\n" "$1"
    eval "$1 $2" &> /dev/null &
  else
    printf "\t\tok\n"
  fi
  sleep 0.3
}

execute_process wmmon
execute_process wmcore
#execute_process wmsysmon
execute_process wmtop
execute_process wmnd "-i eth0"
execute_process wmmon "-s"
execute_process gkrellm "-wm -g +1848+0" 
#execute_process wmwifi "-i 30 -s -bl -tn"
#execute_process wmtimer "-e sound_alert2 -c -t 00:00:00"
#execute_process wmweather "--lcd -m -g  -s SKBO"
#execute_process wmweather+ "-m -mmHg -cm -kph -tempc -metar-station LMML"
#execute_process wmweather+ "-m -mmHg -cm -kph -tempc -metar-station SKBO"
execute_process wmweather+ "-m -mmHg -cm -kph -tempc -metar-station EDDT -location '52.53N 13.43E'"
#execute_process wmpinboard
#execute_process gdeskcal "-x 1001 -y 877"
execute_process wmcliphist "-s 0"
execute_process wmmemload "-as 50 -lc '#ff6666'"
execute_process xbindkeys
execute_process xfce4-power-manager
execute_process gnome-screensaver
execute_process dropboxd
execute_process kbcheckdeamon
execute_process xcompmgr "-C -r1 -o 0.05"
xmodmap .xmodmaprc &> /dev/null &
