#!/bin/sh
###################################################################
# Load hotspot
# 2009-2010 Hpsaturn v1.0
# hpsaturn@gmail.com
#
# REV000: Creación de funciones iniciales. Mode Ad-Hoc soportado
###################################################################

DEVICE=eth1

start_spot () {
    ifconfig $DEVICE down
    sleep 1
    echo -n "set static gateway.."
    ifconfig $DEVICE 192.168.1.1 netmask 255.255.255.0
    ifconfig $DEVICE up
    echo "ok" 
    echo "starting routing.."
    #/etc/init.d/load_iptables restart
    sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
    iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -d 0.0.0.0/0 -j MASQUERADE
    echo "starting dnsmask:"
    cp /etc/dnsmasq_lan.conf /etc/dnsmasq.conf
    service dnsmasq restart
}

stop_spot () {
    stop_services
}

stop_services () {
    echo -n "stop services.."
    ifconfig $DEVICE down
    service dnsmasq stop
    echo "done."
}

case "$1" in
  start)
    start_spot 
    ;;
  stop)
    stop_spot
    ;;
  restart)
    stop_spot
    start_spot
    ;;
  *)
    echo "Usage: load_lannetwork {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

