#! /bin/bash

excute_process () {
  printf "checking\t%.7s" "$1"
  pid=`pidof $1`
  prm=`ps aux | grep -e "$1 $2"`
  if [ "$pid" == "" ] ; then
    printf "\t\trestarting\n"
    eval "$1 $2" &> /dev/null &
  elif [ "$prm" == "" ] ; then 
    printf "\t\tnot same\n"
    printf  "executing\t%.7s\n" "$1"
    eval "$1 $2" &> /dev/null &
  else
    printf "\t\tok\n"
  fi
  sleep 1
}

excute_process xcompmgr "-C -r1 -o 0.05"
excute_process wmmon
excute_process wmcore
#excute_process wmsysmon
excute_process wmtop
excute_process wmnd "-i eth0"
excute_process wmmon "-s"
excute_process gkrellm "-wm -g +1848+0" 
#excute_process wmwifi "-i 30 -s -bl -tn"
#excute_process wmtimer "-e sound_alert2 -c -t 00:00:00"
#excute_process wmweather "--lcd -m -g  -s SKBO"
#excute_process wmweather+ "-m -mmHg -cm -kph -tempc -metar-station LMML"
#excute_process wmweather+ "-m -mmHg -cm -kph -tempc -metar-station SKBO"
excute_process wmweather+ "-m -mmHg -cm -kph -tempc -metar-station EDDT -location '52.53N 13.43E'"
#excute_process wmpinboard
#excute_process gdeskcal "-x 1001 -y 877"
excute_process wmcliphist "-s 0"
excute_process wmmemload "-as 50 -lc '#ff6666'"
excute_process xbindkeys
excute_process xfce4-power-manager
excute_process gnome-screensaver
#killall dropbox
#sleep .5
excute_process dropboxd
excute_process kbcheckdeamon
xmodmap .xmodmaprc &> /dev/null &

