#!/bin/bash
############################################################
# Prerequisites:
#
# In $sdkdir you should have already created the link 
# symbolics to target like this for example:
#
# ndk-bundle -> /home/user/download/android/ndk/ndk-bundle
# tools -> /home/user/download/android/ndk/tools_default
#
# and the alternative, for example:
#
# ndk-bundle -> /home/user/download/android/ndk/android-ndk-r15c
# tools -> /home/user/download/android/ndk/tools_r25.2.5
#

sdkdir=/opt/android-sdk

current_ndk=$(readlink -f $sdkdir/ndk-bundle | sed 's/.*\///')
current_tools=$(readlink -f $sdkdir/tools | sed 's/.*\///')
parent=$(readlink -f $sdkdir/ndk-bundle | sed 's/\(.*\)\/.*/\1/')

if [ "$current_ndk" = "android-ndk-r15c" ]; then
    unlink $sdkdir/ndk-bundle
    #unlink $sdkdir/tools
    ln -s $sdkdir/ndk/20.1.5948944 $sdkdir/ndk-bundle
    #ln -s $parent/tools_default $sdkdir/tools
else
    unlink $sdkdir/ndk-bundle
    #unlink $sdkdir/tools
    ln -s $parent/android-ndk-r15c $sdkdir/ndk-bundle
    #ln -s $parent/tools_r25.2.5 $sdkdir/tools
fi
   
echo ""
echo "==== NEW NDK SETTINGS ===="
echo ""
echo -n "ndk  : "; echo `readlink -f /opt/android-sdk/ndk-bundle | sed 's/.*\///'`
echo -n "tools: "; echo `readlink -f /opt/android-sdk/tools | sed 's/.*\///'`
echo ""

