#!/bin/bash

sdkdir=/opt/android-sdk
current_ndk=$(readlink -f /opt/android-sdk/ndk-bundle | sed 's/.*\///')
current_tools=$(readlink -f /opt/android-sdk/tools | sed 's/.*\///')
parent=$(readlink -f /opt/android-sdk/ndk-bundle | sed 's/\(.*\)\/.*/\1/')

if [ "$current_ndk" = "android-ndk-r15c" ]; then
    unlink $sdkdir/ndk-bundle
    unlink $sdkdir/tools
    ln -s $parent/ndk-bundle $sdkdir/ndk-bundle
    ln -s $parent/tools_default $sdkdir/tools
else
    unlink $sdkdir/ndk-bundle
    unlink $sdkdir/tools
    ln -s $parent/android-ndk-r15c $sdkdir/ndk-bundle
    ln -s $parent/tools_r25.2.5 $sdkdir/tools
fi
   
echo ""
echo "==== NEW NDK SETTINGS ===="
echo ""
echo -n "ndk  : "; echo `readlink -f /opt/android-sdk/ndk-bundle | sed 's/.*\///'`
echo -n "tools: "; echo `readlink -f /opt/android-sdk/tools | sed 's/.*\///'`
echo ""

