#!/bin/bash
for p in ro.product.brand ro.product.manufacturer ro.product.model ro.product.device ro.product.cpu.abi ro.build.description ro.hardware ro.hardware.chipname ro.arch "| grep aaudio"; do echo "$p = $(adb shell getprop $p)"; done

