#!/bin/bash
####################################################################
# ADB clear apk data (GPL license, author: @hpsaturn)
#
# Dependencies: android-tools-adb, dos2unix
#
# Revision:
# -----------------------------------------------------------------
# 20171205 first version (extended from pmstart command)
####################################################################

if [ "$1" = "" ]; then
  echo "usage: pmclear pattern"
  exit 1
fi

pkg=`adb shell 'pm list packages -f' | sed -e 's/.*=//' | grep $1`
cnt=`echo "$pkg" | wc -l`
adb=`echo "$pkg" | sed -e 's/^/adb shell pm clear /'`
cmd=`echo "$adb" | dos2unix`
pkg=`echo "$pkg" | dos2unix`

if [ "$pkg" = "" ]; then
    echo "package not found!"
    exit 1
elif (( $cnt > 1 )); then
    echo ""
    echo "multiple packages found:"
    echo ""
    echo "$pkg"
    echo ""
    exit 1
else
    echo "command: $cmd"
    bash -c "$cmd"
    exit 0
fi

