#!/bin/bash

GNOME_PID=`pidof gnome-screenshot`

if [ "$GNOME_PID" = "" ]; then 
  DATE=`date +%Y%m%d_%H%M%S`             # Date 
  echo "taking screenshot $DATE.jpg"
  gnome-screenshot -f ~/screenshots/screenshot$DATE.jpg "$1"
else
  echo "screenshot instance is running ;|"
fi

