#!/bin/bash
####################################################################
# Snap Package detector for apt packages: This utility attempts to 
# identify possible Snap packages included in the apt repository.
# Designed for users who prefer to avoid Snap packages on Ubuntu, 
# for example :)
#
# @hpsaturn 2024.
#
# Revision:
# -----------------------------------------------------------------
# 20240419 first version
####################################################################

function detect_snap (){
    description=$(apt-cache show "$1")

    cond1=$(echo "$description" | grep 'dummy package')
    cond2=$(echo "$description" | grep 'snap')

    if [ "$cond1" != "" ] && [ "$cond2" != "" ] ; then
        echo "Snap package found in: $1"
    fi
}

function list_all () {
    package_names=$(apt-cache search "dummy package" | awk '{print $1}' | sort)
    for package in $package_names; do
        detect_snap "$package"
    done
}

function showhelp () {
  echo ""
  echo "usage: snapdetector [pattern]"
  echo "usage: snapdetector all"
  echo ""
}

if [ "$1" = "" ]; then
    showhelp
    exit 1
fi

case "$1" in
  all)
    list_all
    ;;
  help)
    showhelp
    ;;
  -h)
    showhelp
    ;;
  *)
    detect_snap "$1"
    ;;
esac

