#!/bin/bash

# Secondary display resolution
Wrt=1920       # Virtual display width (top right)
Hrt=1080       # Virtual display height
Wrb=2160       # Virtual display width (bottom right)
Hrb=1080       # Virtual display height

# Primary display config
P="HDMI-A-0"        #is the main screen, it can be calle eDP-1 or eDP1 depending on the driver
Ort="DisplayPort-0" #can be a virtual (recommended if possible) or real output accepted by the xog driver.
Orb="HDMI-A-1"      #can be a virtual (recommended if possible) or real output accepted by the xog driver.
                    #more info: https://wiki.archlinux.org/title/Extreme_Multihead#VNC
                    #Virtual device using evdi driver:
                    #sudo modprobe evdi initial_device_count=1
                    #xrandr --setprovideroutputsource 1 0

############# END SETUP ##############################################################

showHelp() {
  printf "\r\nusage:\t[start|pause|stop|status|help]\r\n\n"
  printf "start: \tstart xrandr config and vnc servers\r\n"
  printf "pause: \tdisable xrandr virtual screens\r\n"
  printf "stop : \tdisable screens and stop vnc servers\r\n"
  printf "status:\txrandr and vnc servers status\r\n\n"
}

configScreens () {
  # Principal screen width
  PW=`xrandr --current | egrep '\*' | awk '{print $1;}' | cut -d x -f 1 | head -n 1`
  # Create the virtual display
  gtf $Wrt $Hrt 120 | sed '3q;d' | sed 's/Modeline//g' | xargs xrandr --newmode
  gtf $Wrt $Hrt 120 | sed '3q;d' | sed 's/Modeline//g' | awk '{print $1;}' | sed 's/^.\(.*\).$/\1/' | xargs xrandr --addmode $Ort
  gtf $Wrt $Hrt 120 | sed '3q;d' | sed 's/Modeline//g' | awk '{print $1;}' | sed 's/^.\(.*\).$/\1/' | xargs xrandr --output $Ort --right-of $P --mode
  sleep 1
  #gtf $Wrb $Hrb 120 | sed '3q;d' | sed 's/Modeline//g' | xargs xrandr --newmode
  #gtf $Wrb $Hrb 120 | sed '3q;d' | sed 's/Modeline//g' | awk '{print $1;}' | sed 's/^.\(.*\).$/\1/' | xargs xrandr --addmode $Orb
  #gtf $Wrb $Hrb 120 | sed '3q;d' | sed 's/Modeline//g' | awk '{print $1;}' | sed 's/^.\(.*\).$/\1/' | xargs xrandr --output $Orb --below $Ort --mode
  sleep 1
  kill -usr1 `pgrep wmaker | tail -1` # restarting window manager for it recognize the new setup
  sleep 0.5
}

pauseScreens () {
  xrandr --output ${Ort} --off
  sleep 1
  xrandr --output ${Orb} --off
}

startVncServers () {
  # Android device init
  # Forward the VNC port to your device and start a VNC session
  # adb reverse tcp:5900 tcp:5900 # uncomment for Android secondary display
  echo "Starting VNC server"
  x11vnc -bg -display :0 -clip ${Wrt}x${Hrt}+${PW}+0 -rfbport 5900 -repeat -forever -nonap -multiptr -noxfixes
  sleep 1
  #x11vnc -bg -display :0 -clip ${Wrb}x${Hrb}+${PW}+${Hrt} -rfbport 5901 -repeat -forever -nonap -multiptr -noxfixes
  #
  # On the old laptop please run:
  # vncviewer -shared -ViewOnly -Fullscreen <host ip>
}

stopVncServers () {
  x11vnc -R stop
  x11vnc -clear-all
}

screenStatus () {
  printf "\r\nMain display and virtual screens:\r\n\n"
  xrandr --display :0 | grep connected | awk '{print $1}'
  printf "\r\nX11 VNC servers running on:\r\n\n"
  ps aux | grep x11vnc | grep rfbport | awk '{print $18}'
}


if [ "$1" = "" ]; then
  showHelp
else
    case "$1" in
        start)
            configScreens
            startVncServers
            ;;
        pause)
            pauseScreens
            ;;
        stop)
            pauseScreens
            stopVncServers
            ;;
        status)
            screenStatus
            ;;
        help)
            showHelp
            ;;
        *)
            showHelp
            ;;
    esac
fi


